export const darkTheme = {
  bg: '#000',
  card: '#1A1A1A',
  border: '#2A2A2A',
  border2: '#333',
  textPrimary: '#fff',
  textSecondary: '#888',
  textMuted: '#444',
  textTertiary: '#666',
  inputBg: '#1A1A1A',
  pickBg: '#2c2c2c',
  pickBorder: '#717171',
  emptyIcon: '#333',
  retryBg: '#1A1A1A',
  qualityTitle: '#ccc',
  sectionSubtitle: '#aaa',
  saveBtnBg: '#fff',
  shareBtnBg: '#fff',
  saveBtnText: '#24bd6c',
  shareBtnText: '#2E86DE',
  toggleInnerBg: '#111',
  modalBg: '#111',
  blurType: 'dark',
};

export const lightTheme = {
  bg: '#F5F5F5',
  card: '#FFFFFF',
  border: '#E0E0E0',
  border2: '#DCDCDC',
  textPrimary: '#111',
  textSecondary: '#555',
  textMuted: '#999',
  textTertiary: '#777',
  inputBg: '#EFEFEF',
  pickBg: '#E8E8E8',
  pickBorder: '#BBBBBB',
  emptyIcon: '#CCC',
  retryBg: '#F0F0F0',
  qualityTitle: '#444',
  sectionSubtitle: '#666',
  saveBtnBg: '#22C55E',
  shareBtnBg: '#2E86DE',
  saveBtnText: '#fff',
  shareBtnText: '#fff',
  toggleInnerBg: '#DDDDDD',
  modalBg: '#FFFFFF',
  blurType: 'light',
};
